ode:
  name: dupont_1991b

  parameters:
    v0: 1.0

    v1: 7.3

    VM2: 65.0

    VM3: 500.0

    KR: 2.0

    KA: 0.9

    kf: 1.0

    k: 10.0

    K2: 1.0

    n: 2.0

    m: 2.0

    p: 4.0

    betaf: 0.96

    tp: 4

  initial_state:
    Z: 0.52

    Y: 0.93

  parameter_names:
    - v0
    - v1
    - VM2
    - VM3
    - KR
    - KA
    - kf
    - k
    - K2
    - n
    - m
    - p
    - betaf
    - tp

  state_names:
    - Z
    - Y
